from typing import Iterator, Protocol

from src.domain.task import Task


class TaskQueue(Protocol):
    def get_ready_for_execution_tasks(self) -> Iterator[Task]: ...
    def get_highest_priority_task(self) -> Task | None: ...
    def filter_by_status(self, status: int) -> Iterator[Task]: ...
    def filter_by_priority(self, priority: int) -> Iterator[Task]: ...
    def filter_by_id(self, task_id: int) -> Iterator[Task]: ...
    def __iter__(self) -> Iterator[Task]: ...
    def add_task(self, task: Task) -> Task | None: ...
    def delete_task_by_id(self, task_id: int) -> Task | None: ...
    def get_task_by_id(self, task_id: int) -> Task | None: ...
    def update_task_by_id(
        self, task_id: int, new_task: Task
    ) -> Task | None: ...
